In [509]:
import numpy as np

In [510]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,6,5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [511]:
type(a)# ndarray is n-dimensional array

numpy.ndarray

In [512]:
print(a+b)
print(a-b)
print(a*b)

[9 9 9 9 9 9 9 9]
[-7 -5 -3 -1  1  3  5  7]
[ 8 14 18 20 20 18 14  8]


In [513]:
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [514]:
#3d array
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [515]:
print(a2.shape)
print(a3.ndim)#type of array ex 3d or 2d
print(a2.dtype)#type of datatype

(2, 2)
3
int64


In [516]:
np.arange(10)
np.arange(2,21)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [517]:
np.random.randint(1,11, size=(2,3))

array([[1, 9, 8],
       [4, 5, 5]], dtype=int32)

In [518]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3],])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [519]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [520]:
print(x@y) #matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [521]:
np.dot(x,y) #matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [522]:
x.prod() #product of all elements of the array

np.int64(12600)

In [523]:
x.mean() #mean of all elements

np.float64(3.3333333333333335)

In [524]:
y.mean()

np.float64(3.7777777777777777)

In [525]:
x.mean(axis = 0) #column wise mean

array([4., 4., 2.])

In [526]:
y.mean(axis = 1) #row wise mean

array([4.        , 4.        , 3.33333333])

In [527]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [528]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,50)) #median
print(np.percentile(a,75)) #3rd quartrile

3.0
5.0
7.0


In [529]:
b = np.random.randint(11,100, (4,4))
print(b)

[[48 44 91 13]
 [19 43 50 95]
 [81 81 59 96]
 [69 24 91 92]]


In [530]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[48 44 91 13 19 43 50 95]
 [81 81 59 96 69 24 91 92]]
8X2
[[48 44]
 [91 13]
 [19 43]
 [50 95]
 [81 81]
 [59 96]
 [69 24]
 [91 92]]


In [532]:
x = np.random.randint(1,11 ,(5,5))
print(x)

[[10  4  6  7  8]
 [ 5  9  3  8  1]
 [ 4  2  9  2  9]
 [ 3  2 10  3  1]
 [ 7  2  2 10  5]]


In [536]:
print(x[0]) #1st row
print(x[0,1]) #1st row and 2nd column's first element
print(x[-1])

print(x[:3])
print(x[3:])

[10  4  6  7  8]
4
[ 7  2  2 10  5]
[[10  4  6  7  8]
 [ 5  9  3  8  1]
 [ 4  2  9  2  9]]
[[ 3  2 10  3  1]
 [ 7  2  2 10  5]]
